//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenBoard.WinForms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Allergen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Allergen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CanteenBoard.WinForms.Resources.Allergen", typeof(Allergen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celery.
        /// </summary>
        internal static string Celery {
            get {
                return ResourceManager.GetString("Celery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cereals.
        /// </summary>
        internal static string Cereals {
            get {
                return ResourceManager.GetString("Cereals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crustaceans.
        /// </summary>
        internal static string Crustaceans {
            get {
                return ResourceManager.GetString("Crustaceans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggs.
        /// </summary>
        internal static string Eggs {
            get {
                return ResourceManager.GetString("Eggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        internal static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lupin.
        /// </summary>
        internal static string Lupin {
            get {
                return ResourceManager.GetString("Lupin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milk.
        /// </summary>
        internal static string Milk {
            get {
                return ResourceManager.GetString("Milk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molluscs.
        /// </summary>
        internal static string Molluscs {
            get {
                return ResourceManager.GetString("Molluscs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mustard.
        /// </summary>
        internal static string Mustard {
            get {
                return ResourceManager.GetString("Mustard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuts.
        /// </summary>
        internal static string Nuts {
            get {
                return ResourceManager.GetString("Nuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peanuts.
        /// </summary>
        internal static string Peanuts {
            get {
                return ResourceManager.GetString("Peanuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesame.
        /// </summary>
        internal static string Sesame {
            get {
                return ResourceManager.GetString("Sesame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soybeans.
        /// </summary>
        internal static string Soybeans {
            get {
                return ResourceManager.GetString("Soybeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SulphurDioxide.
        /// </summary>
        internal static string SuplhurDioxide {
            get {
                return ResourceManager.GetString("SuplhurDioxide", resourceCulture);
            }
        }
    }
}
